### ISSUE TITLE
No verbose or debug log output

### ISSUE THREAD

**Issue by ragnvaldr** [asticode/go-astilog#6]
I'm sure I'm missing something obvious, but I'm new to astilectron and can't figure out where the astilog output goes... Should it be saving to a file somewhere? If so, where? And can it be configured to output to a specific dir/file? 

I tried running the go-astilectron-demo-master with -v flag and there's no console output or files that I can find. 
Also tried changing 	debug   = flag.Bool("d", false, "enables debug logging") to true, rebuilt, and ran with -d flag. 

Running it on Win 10, building with astilectron-bundler
Thanks

**Comment by asticode** [comment]
When using the `-v` flag and running the binary directly, it should output in the console. But Windows might be an exception since I have seen `Avast` causing problems with this for instance.

What you can try is using the `Filename` configuration attribute of the logger. If set, it should log everything to this file.

Let me know how it goes.

**Comment by ragnvaldr** [comment]
Okay, thanks. I did try the Filename flag, but still no luck.

To confirm, it should be something like:

```
var (
	AppName string
	BuiltAt string
	debug   = flag.Bool("d", false, "enables debug logging")
	Filename = flag.String("astilog-output.log", "", "the logger's filename")
	w       *astilectron.Window
)

```
Is the filepath relative to the exe? Can it be set to a full filepath? Eg. "D:\\logs\\astilog-output.log" neither have worked so far

Is there any additional flag besides -v I need? I've also tried with debug flag true and with the -d flag

**Comment by ragnvaldr** [comment]
Okay, so I spun up an ubuntu machine to try and replicate. Confirmed -v output to console as expected, and it also gave me this output that I didn't get from Windows, so now I at least know how to save the log to a file by CLI and think I understand what I was doing wrong


```
  -astilog-output.log string
    	logging output filename
  -d	enables debug logging
  -logger-app-name string
    	the logger's app name
  -logger-filename string
    	the logger's filename
  -v	if true, then log level is debug
```

Is there a way to save this automatically in the build without needing the CLI flag? 

Thanks for the help

**Comment by asticode** [comment]
@ragnvaldr I wasn't clear enough regarding the `Filename` attribute. You should replace the `astilog.FlagInit()` (if present) or any other `astilog.SetLogger()` method that you find and replace it by this at the top of your `main` function:

```go
astilog.SetLogger(astilog.New(astilog.Configuration{
	Filename: "/path/to/file",
	Verbose: true,
}))
```

This will set up the logger so that it logs to a file.

**Comment by ragnvaldr** [comment]
Okay, thanks for the clarification. Much appreciated.
