### ISSUE TITLE
-v flag causing pain

### ISSUE THREAD

**Issue by jasonhancock** [asticode/go-astilog#7]
Globally defining a generic flag like `-v` should be avoided. Can the flag be renamed with a prefix like the other flags (something like `logger-verbose`) or can the flag registration be an opt-in rather than a side-effect of package import?

**Comment by asticode** [comment]
You're right, that's a mistake that was following me around for quite some time! I've renamed the flag to `-logger-verbose` and added a `SetHandyFlags()` method that sets the flag back to `-v`.
Cheers
